"use strict";
const pptxgen=require("pptxgenjs");
const {autoFontSize,imageSizingContain,warnIfSlideHasOverlaps,warnIfSlideElementsOutOfBounds}=require("./pptxgenjs_helpers");
const path=require("path");
const pptx=new pptxgen();
pptx.layout="LAYOUT_WIDE";pptx.author="OpenAI Codex";pptx.company="Bảo Việt Nhân Thọ";pptx.lang="vi-VN";pptx.theme={headFontFace:"Barlow",bodyFontFace:"Barlow",lang:"vi-VN"};
const W=13.333,H=7.5,C={b:"0B6CB8",bd:"114A7A",g:"C99211",gd:"9F720C",t:"203040",s:"5C6C7B",l:"F6F8FB",ln:"D8E0E8",w:"FFFFFF"};
const hero=path.join(__dirname,"master_unzip","ppt","media","image2.jpg");
const base=path.join(__dirname,"master_unzip","ppt","media","image3.png");
const bg=(sl,k="base")=>sl.addImage({path:k==="hero"?hero:base,...imageSizingContain(k==="hero"?hero:base,0,0,W,H)});
const t=(sl,tx,x,y,w,h,o={})=>sl.addText(tx,{x,y,w,h,fontFace:o.ff||"Barlow",fontSize:o.fs||12,color:o.c||C.t,bold:!!o.b,italic:!!o.i,margin:o.m??0,align:o.a||"left",valign:o.v||"top",breakLine:o.br??true});
const kicker=(sl,tx)=>t(sl,tx.toUpperCase(),0.9,0.72,3.8,0.2,{fs:10,c:C.gd,b:true});
function title(sl,ttl,sub){sl.addText(ttl,{x:0.9,y:0.98,w:8.85,h:0.62,fontFace:"Barlow",bold:true,color:C.bd,margin:0,...autoFontSize(ttl,"Barlow",{x:0.9,y:0.98,w:8.85,h:0.62,fontSize:24,minFontSize:22,maxFontSize:28,bold:true,margin:0,mode:"auto"})}); if(sub)t(sl,sub,0.9,1.67,8.9,0.34,{fs:11,c:C.s});}
const num=(sl,n)=>t(sl,String(n).padStart(2,"0"),12.45,7.03,0.4,0.18,{fs:9,c:C.gd,b:true,a:"right"});
const pill=(sl,tx,x,y,w,c=C.g)=>{sl.addShape(pptx.ShapeType.roundRect,{x,y,w,h:0.34,rectRadius:0.08,fill:{color:c,transparency:8},line:{color:c,pt:0}});t(sl,tx,x+0.06,y+0.08,w-0.12,0.14,{fs:9.2,c:C.w,b:true,a:"center"});};
const card=(sl,x,y,w,h,hd,big,small,accent=C.b)=>{sl.addShape(pptx.ShapeType.roundRect,{x,y,w,h,rectRadius:0.05,fill:{color:C.w},line:{color:C.ln,pt:1}});sl.addShape(pptx.ShapeType.rect,{x:x+0.14,y:y+0.14,w:0.05,h:h-0.28,fill:{color:accent},line:{color:accent,pt:0}});t(sl,hd,x+0.28,y+0.14,w-0.36,0.16,{fs:9.2,c:C.s});t(sl,big,x+0.28,y+0.38,w-0.36,0.28,{fs:18,b:true,c:C.bd});if(small)t(sl,small,x+0.28,y+0.74,w-0.36,h-0.84,{fs:8.8,c:C.s});};
const box=(sl,x,y,w,h,ttl,arr,foot)=>{sl.addShape(pptx.ShapeType.roundRect,{x,y,w,h,rectRadius:0.05,fill:{color:C.w},line:{color:C.ln,pt:1}});sl.addShape(pptx.ShapeType.rect,{x:x+0.24,y:y+0.18,w:1.1,h:0.05,fill:{color:C.g},line:{color:C.g,pt:0}});t(sl,ttl,x+0.24,y+0.3,w-0.48,0.26,{fs:17.5,b:true,c:C.bd});arr.forEach((it,i)=>sl.addText([{text:it,options:{bullet:{indent:12}}}],{x:x+0.24,y:y+0.8+i*0.4,w:w-0.58,h:0.22,fontFace:"Barlow",fontSize:11.4,color:C.t,margin:0}));if(foot){sl.addShape(pptx.ShapeType.roundRect,{x:x+0.2,y:y+h-0.52,w:w-0.4,h:0.28,rectRadius:0.03,fill:{color:"F7F3E8"},line:{color:"F7F3E8",pt:0}});t(sl,foot,x+0.28,y+h-0.45,w-0.56,0.12,{fs:8.8,c:C.gd,b:true});}};
const quote=(sl,tx,src)=>{sl.addShape(pptx.ShapeType.roundRect,{x:0.9,y:5.86,w:8.1,h:0.92,rectRadius:0.05,fill:{color:C.l},line:{color:"E7EDF4",pt:1}});t(sl,`“${tx}”`,1.14,6.06,7.5,0.3,{fs:13.2,c:C.bd,i:true});t(sl,src,1.14,6.46,3,0.14,{fs:9,c:C.s});};
function finalize(sl,n){num(sl,n);warnIfSlideHasOverlaps(sl,pptx);warnIfSlideElementsOutOfBounds(sl,pptx);} 
function content(n,k,ttl,sub,fn){const sl=pptx.addSlide();bg(sl);kicker(sl,k);title(sl,ttl,sub);fn(sl);finalize(sl,n);} 
function section(n,label,ttl,sub){const sl=pptx.addSlide();bg(sl,"hero");sl.addShape(pptx.ShapeType.rect,{x:0.92,y:2.02,w:0.1,h:2.02,fill:{color:C.b},line:{color:C.b,pt:0}});t(sl,label.toUpperCase(),1.18,2.06,2.4,0.18,{fs:10,c:C.w,b:true});sl.addText(ttl,{x:1.18,y:2.38,w:8.3,h:1.1,fontFace:"Barlow",bold:true,color:C.w,margin:0,...autoFontSize(ttl,"Barlow",{x:1.18,y:2.38,w:8.3,h:1.1,fontSize:28,minFontSize:24,maxFontSize:34,bold:true,margin:0,mode:"auto"})});t(sl,sub,1.18,3.68,6.8,0.48,{fs:14,c:C.w});finalize(sl,n);} 
const slides=[
{type:"hero",ttl:"GIẢI VÔ ĐỊCH ĐUA GHE TRUYỀN THỐNG CỐ ĐÔ HUẾ 2026\nTRANH CÚP BẢO VIỆT NHÂN THỌ",sub:"Big Idea đề xuất: GIỮ MÁI CHÈO DI SẢN",line:"Bảo Việt Nhân Thọ - Giữ mái chèo hôm nay, chở che muôn thế hệ mai sau."},
{type:"section",label:"Mở đầu",ttl:"Tham vọng không dừng ở một sự kiện. Tham vọng là tạo ra tài sản văn hóa mang tên Bảo Việt Nhân Thọ.",sub:"Từ một giải đua ghe truyền thống của Huế, nâng tầm thành điểm hẹn văn hóa - cảm xúc - cộng đồng mang sức lan tỏa quốc gia."},
{type:"why"},
{type:"two",k:"Cultural Context",ttl:"Huế không chỉ là bối cảnh. Huế chính là linh hồn của đề xuất.",sub:"Ở Huế, sông là ký ức, là đời sống, là nơi truyền thống được nối tiếp.",l:{t:"Huế là thành phố của chiều sâu",i:["Ký ức đô thị gắn với sông Hương, Phu Văn Lâu, nhịp sống cố đô.","Vẻ đẹp của Huế nằm ở sự gìn giữ, chuẩn mực và chiều sâu cảm xúc.","Tinh thần gia phong, truyền đời và trân trọng cội nguồn rất rõ nét."]},r:{t:"Đua ghe là nghi lễ sống",i:["Mỗi chiếc ghe vận hành như một gia đình: cùng nhịp, cùng gánh, cùng vượt sóng.","Người cầm lái là biểu tượng của trách nhiệm và sự dẫn dắt.","Khán giả dọc hai bờ sông tạo nên tính lễ hội xã hội rất mạnh."]}},
{type:"insight"},
{type:"two",k:"Opportunity",ttl:"Bài toán thương hiệu và cơ hội mở khóa",sub:"Bảo Việt Nhân Thọ cần nhiều hơn nhận biết. Thương hiệu cần một không gian để củng cố niềm tin bằng cảm xúc và văn hóa.",l:{t:"Brand problem",i:["Thông điệp bảo vệ gia đình là đúng nhưng thường nghe quen.","Các điểm chạm truyền thông nhanh nhưng ít tài sản sở hữu lâu dài.","Thương hiệu cần được cảm nhận như một người đồng hành đáng tin."],f:"Need: một platform có chiều sâu biểu tượng và khả năng lặp lại."},r:{t:"Brand opportunity",i:["Trở thành người giữ nhịp cho một nghi lễ cộng đồng được mong đợi.","Biến giá trị 'bảo vệ sự tiếp nối' thành trải nghiệm nhìn thấy và cảm được.","Mở ra hệ IMC đủ lớn để kể câu chuyện thương hiệu ở phạm vi quốc gia."],f:"Outcome: từ sponsor thành cultural custodian."}},
{type:"role"},
{type:"platform"},
{type:"two",k:"Big Idea",ttl:"Big Idea đề xuất: GIỮ MÁI CHÈO DI SẢN",sub:"Một câu nói gói được cả gia đình, người trụ cột, di sản Huế và vai trò bảo vệ của thương hiệu.",l:{t:"Vì sao mạnh",i:["Mái chèo đại diện cho người giữ nhịp và trách nhiệm.","Di sản mở rộng từ di sản Huế sang di sản gia đình.","Chữ 'giữ' rất gần với vai trò cốt lõi của bảo hiểm nhân thọ."],f:"Một câu có thể dùng cho event, film, social, PR và nhiều mùa sau."},r:{t:"Vì sao hợp Bảo Việt",i:["Ngôn ngữ sang trọng, có chiều sâu, không phô trương bán hàng.","Chạm cảm xúc gia đình mà vẫn giữ sự chuẩn mực của thương hiệu lớn.","Mở ra một tài sản thương hiệu có thể sở hữu bằng naming rights."],f:"Đủ premium cho boardroom và đủ lan tỏa cho đại chúng."}},
{type:"msg"},
{type:"win"},
{type:"section",label:"Tầm nhìn sự kiện",ttl:"Biến cuộc đua thành một hiện tượng văn hóa đương đại của Huế và của cả thương hiệu.",sub:"Thiết kế lại event như một ritual premium trên sông Hương: có nghi thức mở màn, có spectacle thị giác, có lớp nội dung để khán giả muốn xem, muốn chia sẻ, muốn quay lại."},
{type:"two",k:"WOW Moment 01",ttl:"Lễ Tôn Vinh Người Cầm Lái",sub:"Khoảnh khắc mở màn giàu biểu tượng: đồng loạt 20 đội dựng mái chèo và hướng về bờ danh dự.",l:{t:"Mô tả trải nghiệm",i:["Người cầm lái 20 đội ghe được xướng danh trước giờ xuất phát.","Đồng loạt dựng mái chèo trên mặt sông như một hàng cột di sản.","Âm thanh trống - hô lệnh - dàn nhạc dân tộc phối khí đương đại."]},r:{t:"Giá trị truyền thông",i:["Đặt Bảo Việt Nhân Thọ vào vai trò tôn vinh người giữ nhịp.","Tạo visual signature mà báo chí, TV và social đều muốn ghi lại.","Dễ cắt thành short-form video giàu cảm xúc và self-pride."]}},
{type:"wow2"},
{type:"two",k:"WOW Moment 03",ttl:"Drone Tribute - Giữ Mái Chèo Di Sản",sub:"Một biểu tượng trên bầu trời để tuyên bố rằng cuộc đua này đã bước sang đẳng cấp mới.",l:{t:"Kịch bản hình ảnh",i:["Biểu tượng mái chèo - con ghe - sông Hương - cúp Bảo Việt Nhân Thọ.","Sequence: Giữ mái chèo. Giữ dòng chảy. Giữ gia đình đi tiếp.","Kết thúc bằng nhận diện event năm đầu như một lời hẹn mùa sau."]},r:{t:"Giá trị vượt event",i:["Tạo lượng nội dung UGC và earned media lớn trên toàn quốc.","Giúp giải đấu thoát khỏi cảm giác 'địa phương' để thành national spectacle.","Khóa định vị cho Bảo Việt Nhân Thọ như nhà tài trợ làm văn hóa xứng tầm."]}},
{type:"journey"},
{type:"section",label:"IMC",ttl:"Biến một ngày trên sông thành một chiến dịch nhiều lớp, nhiều pha, nhiều cơ hội chuyển đổi.",sub:"Cấu trúc IMC được thiết kế để kéo dài sức nóng trước - trong - sau sự kiện, đồng thời gắn awareness với trust và lead generation."},
{type:"imc"},
{type:"two",k:"Phase 1",ttl:"Giai đoạn 1 - Teasing: dựng ý nghĩa trước khi dựng sân khấu",sub:"Khiến công chúng cảm thấy đây không chỉ là một cuộc đua, mà là một biểu tượng đáng chờ đợi.",l:{t:"Nội dung mồi cảm xúc",i:["Short video 'Ai là người giữ nhịp trong gia đình bạn?'.","Poster series về mái chèo, bàn tay, dòng sông, vai người trụ cột.","Key visual countdown gắn với Quốc khánh và Huế."]},r:{t:"PR & cộng đồng",i:["PR khởi động naming rights và tầm nhìn nâng cấp giải đấu.","Kể chuyện các đội ghe, người cầm lái, ký ức đua ghe của Huế.","Local seeding tại Huế, Đà Nẵng và các cộng đồng yêu văn hóa."]}},
{type:"phase2"},
{type:"two",k:"Phase 3",ttl:"Giai đoạn 3 - Amplification & Legacy",sub:"Sau cuộc đua, tài sản truyền thông và dữ liệu không kết thúc. Nó phải tiếp tục nuôi thương hiệu.",l:{t:"Amplification",i:["Aftermovie brand film và recap film cho event.","Photo essay / quote cards về người cầm lái, gia đình, đội ghe thắng cuộc.","PR tổng kết: từ sự kiện cộng đồng đến tài sản văn hóa mới."]},r:{t:"Legacy",i:["Xuất bản 'Sổ tay Giữ Mái Chèo' dạng nội dung thương hiệu nhẹ nhàng.","Nurturing lead theo nhóm đã tương tác / để lại lời nhắn / check-in.","Mở lời hẹn cho mùa giải 2027 với thông báo sớm về platform."]}},
{type:"activation"},
{type:"two",k:"Social & PR",ttl:"Chiến lược social, PR, KOL/KOC và viral mechanics",sub:"Tạo độ phủ bằng nhiều lớp người kể chuyện, không phụ thuộc vào một viral stunt đơn lẻ.",l:{t:"Social mechanics",i:["TikTok challenge: #GiuNhipGiaDinh với format kể về người giữ nhịp trong nhà.","UGC format: viết một câu nhắn cho 'mái chèo' của gia đình mình.","Realtime templates cho story, frame check-in và sticker event."]},r:{t:"PR & influencer",i:["Local KOL: nghệ sĩ Huế, travel creator, cultural storyteller.","National KOL: family voices, lifestyle MC, documentary-style creator.","PR angle chia 3 nhánh: văn hóa Huế, sự kiện Quốc khánh, vai trò thương hiệu."]}},
{type:"film"},
{type:"ecosystem"},
{type:"two",k:"Branding Integration",ttl:"Cơ hội tích hợp thương hiệu trong event",sub:"Hiện diện thương hiệu cần rõ ràng nhưng phải giữ được độ sang và sự tôn trọng bối cảnh văn hóa.",l:{t:"Visible branding",i:["Tên giải đấu, cúp vô địch, backdrop, podium, uniform key crew.","Hệ banner ven sông, pontoon, media wall, livestream package.","Merch premium chọn lọc: khăn, nón, pin, thẻ sự kiện."]},r:{t:"Meaningful branding",i:["Nghi lễ tôn vinh người cầm lái mang tên Bảo Việt Nhân Thọ.","Không gian lời nhắn gia đình và cúp di sản có thương hiệu đồng hành.","Giải phụ cho câu chuyện cộng đồng / đội ghe truyền cảm hứng."]}},
{type:"lead"},
{type:"impact"},
{type:"kpi"},
{type:"annual"},
{type:"close"}
];
slides.forEach((s,idx)=>{
const n=idx+1;
if(s.type==="hero"){const sl=pptx.addSlide();bg(sl,"hero");t(sl,"ĐỀ XUẤT NỀN TẢNG TÀI TRỢ VĂN HÓA - THƯƠNG HIỆU",0.9,2.08,4.5,0.2,{fs:10,c:C.bd,b:true});sl.addText(s.ttl,{x:0.9,y:2.72,w:8.8,h:1.18,fontFace:"Barlow",bold:true,color:C.bd,margin:0,...autoFontSize(s.ttl,"Barlow",{x:0.9,y:2.72,w:8.8,h:1.18,fontSize:23,minFontSize:21,maxFontSize:26,bold:true,margin:0,mode:"auto"})});t(sl,s.sub,0.9,4.18,4.8,0.24,{fs:15,c:C.w,b:true});t(sl,s.line,0.9,4.52,5.8,0.3,{fs:12.8,c:C.w});pill(sl,"02.09.2026 | SÔNG HƯƠNG - HUẾ",0.9,5.02,2.95,C.b);pill(sl,"TITLE SPONSOR / NAMING RIGHTS",3.98,5.02,3.2,C.g);quote(sl,"Không chỉ tài trợ một cuộc đua. Đây là cơ hội để Bảo Việt Nhân Thọ sở hữu một tài sản văn hóa sống cùng gia đình Việt qua nhiều năm.","Định hướng đề xuất chiến lược");finalize(sl,n);return;}
if(s.type==="section"){section(n,s.label,s.ttl,s.sub);return;}
if(s.type==="two"){content(n,s.k,s.ttl,s.sub,sl=>{box(sl,0.9,2.18,5.63,3.7,s.l.t,s.l.i,s.l.f);box(sl,6.82,2.18,5.63,3.7,s.r.t,s.r.i,s.r.f);});return;}
if(s.type==="why"){content(n,"Bối cảnh chiến lược","Vì sao dự án này đáng để làm ngay lúc này","Một thời điểm hiếm khi cả giá trị văn hóa, tinh thần Quốc khánh và nhu cầu thương hiệu cùng hội tụ.",sl=>{card(sl,0.9,2.2,2.8,1.22,"Quốc khánh 02/09","Khoảnh khắc quốc gia","Tinh thần đoàn kết và niềm tự hào cộng đồng",C.g);card(sl,3.86,2.2,2.8,1.22,"Huế","Di sản sống","Thành phố của ký ức, kế thừa và chiều sâu cảm xúc",C.b);card(sl,6.82,2.2,2.8,1.22,"Đua ghe truyền thống","Nghi lễ cộng đồng","Mang tính biểu tượng, dễ tạo spectacle hình ảnh",C.g);card(sl,9.78,2.2,2.65,1.22,"Bảo Việt Nhân Thọ","Thương hiệu bảo vệ","Phù hợp tự nhiên với vai trò giữ dòng chảy gia đình",C.b);sl.addShape(pptx.ShapeType.roundRect,{x:0.9,y:3.75,w:11.55,h:1.88,rectRadius:0.05,fill:{color:C.l},line:{color:C.ln,pt:1}});t(sl,"Nếu làm như một gói tài trợ logo, giá trị sẽ dừng ở hiện diện. Nếu làm như một nền tảng văn hóa thường niên, Bảo Việt Nhân Thọ sẽ sở hữu một biểu tượng cảm xúc có khả năng tích lũy qua từng năm.",1.18,4.08,8.8,0.54,{fs:15.5,c:C.bd,b:true});["Đủ lớn để tạo trải nghiệm thực địa, livestream và PR quốc gia.","Đủ sâu về văn hóa để kể câu chuyện bảo vệ gia đình một cách tinh tế.","Đủ khác biệt để trở thành signature property thay vì activation ngắn hạn."].forEach((it,i)=>sl.addText([{text:it,options:{bullet:{indent:12}}}],{x:1.18,y:4.84+i*0.24,w:7,h:0.2,fontFace:"Barlow",fontSize:12.2,color:C.t,margin:0}));});return;}
if(s.type==="insight"){content(n,"Insight","Sâu bên trong mọi gia đình Việt luôn có một nỗi lo rất giống nhau","Người ta không sợ sóng gió xuất hiện. Người ta sợ hành trình gia đình phải dừng lại giữa dòng.",sl=>{[["GHE","Gia đình"],["MÁI CHÈO","Người trụ cột"],["DÒNG SÔNG","Cuộc đời"],["SÓNG GIÓ","Rủi ro"]].forEach((a,i)=>{const x=0.9+i*2.9;sl.addShape(pptx.ShapeType.roundRect,{x,y:2.18,w:2.55,h:0.72,rectRadius:0.04,fill:{color:i%2===0?"F8F3E8":"EEF5FB"},line:{color:C.ln,pt:1}});t(sl,a[0],x+0.18,2.34,0.75,0.14,{fs:10,b:true,c:i%2===0?C.gd:C.b});t(sl,a[1],x+0.18,2.52,1.85,0.16,{fs:14,b:true,c:C.bd});});sl.addShape(pptx.ShapeType.roundRect,{x:0.9,y:3.15,w:7.1,h:2.1,rectRadius:0.05,fill:{color:C.bd},line:{color:C.bd,pt:0}});t(sl,"Khi một nhịp chèo chậm lại, cả con ghe đều bị ảnh hưởng. Khi người trụ cột gặp biến cố, nỗi lo lớn nhất là liệu gia đình có còn đi tiếp được như trước hay không.",1.16,3.52,6.55,0.9,{fs:20,b:true,c:C.w});sl.addShape(pptx.ShapeType.roundRect,{x:8.25,y:3.15,w:4.2,h:2.1,rectRadius:0.05,fill:{color:C.w},line:{color:C.ln,pt:1}});t(sl,"Ý nghĩa với Bảo Việt Nhân Thọ",8.5,3.42,2.8,0.16,{fs:10,b:true,c:C.gd});["Bảo hiểm nhân thọ không chỉ là tài chính.","Đó là lời hứa giữ cho hành trình gia đình không bị ngắt mạch.","Đua ghe Huế là ẩn dụ Việt Nam và giàu cảm xúc nhất cho lời hứa đó."].forEach((it,i)=>sl.addText([{text:it,options:{bullet:{indent:12}}}],{x:8.48,y:3.76+i*0.34,w:3.45,h:0.24,fontFace:"Barlow",fontSize:11.4,color:C.t,margin:0}));});return;}
if(s.type==="role"){content(n,"Brand Role","Vai trò của Bảo Việt Nhân Thọ trong dự án này phải lớn hơn một nhà tài trợ","Thương hiệu là người giữ cho cuộc đua tiếp tục, cũng như giữ cho hành trình của mỗi gia đình không ngừng lại.",sl=>{sl.addShape(pptx.ShapeType.roundRect,{x:0.9,y:2.25,w:11.55,h:3.2,rectRadius:0.05,fill:{color:C.w},line:{color:C.ln,pt:1}});[["Title sponsor","Không chỉ đặt tên giải đấu mà đặt tên cho một chuẩn mực tổ chức mới."],["Guardian of continuity","Bảo vệ sự tiếp nối của gia đình, cộng đồng và một di sản văn hóa sống."],["Curator of cultural pride","Tôn vinh Huế bằng cách nâng nghi lễ truyền thống lên tầm trải nghiệm quốc gia."]].forEach((c,i)=>{const x=1.15+i*3.74;sl.addShape(pptx.ShapeType.roundRect,{x,y:2.72,w:3.15,h:2.15,rectRadius:0.05,fill:{color:C.l},line:{color:"E8EEF5",pt:1}});pill(sl,`0${i+1}`,x+0.18,2.9,0.48,i===1?C.g:C.b);t(sl,c[0],x+0.18,3.28,2.7,0.24,{fs:15.5,b:true,c:C.bd});t(sl,c[1],x+0.18,3.68,2.7,0.72,{fs:11.1});});quote(sl,"Khi thương hiệu giữ được nhịp của một di sản, thương hiệu cũng giữ được nhịp của niềm tin.","Brand role statement");});return;}
if(s.type==="platform"){content(n,"Strategic Platform","Lãnh thổ chiến lược trung tâm","BẢO VIỆT GIỮ CHO DÒNG CHẢY GIA ĐÌNH KHÔNG NGỪNG LẠI",sl=>{sl.addShape(pptx.ShapeType.roundRect,{x:0.9,y:2.28,w:11.55,h:2.76,rectRadius:0.05,fill:{color:C.bd},line:{color:C.bd,pt:0}});t(sl,"Đây là platform đủ rộng để kể câu chuyện bảo vệ gia đình, đủ sâu để chạm vào văn hóa Huế, và đủ linh hoạt để mở rộng thành tài sản thường niên của thương hiệu.",1.18,2.68,10.9,0.6,{fs:17.5,c:C.w,b:true});["Brand truth: Bảo Việt Nhân Thọ bảo vệ sự tiếp nối.","Human truth: Gia đình luôn cần một điểm tựa để đi tiếp qua biến động.","Cultural truth: Huế tôn vinh ký ức, truyền đời và sự gìn giữ."].forEach((it,i)=>sl.addText([{text:it,options:{bullet:{indent:12}}}],{x:1.18,y:3.56+i*0.26,w:6.2,h:0.2,fontFace:"Barlow",fontSize:12.2,color:C.w,margin:0}));pill(sl,"EMOTIONAL",8.0,3.48,1.16,C.g);pill(sl,"CULTURAL",9.28,3.48,1.16,C.b);pill(sl,"SCALABLE",10.56,3.48,1.3,C.g);t(sl,"Một platform vừa bán được ý nghĩa, vừa xây được di sản thương hiệu.",8.0,4.02,3.2,0.36,{fs:12.8,c:C.w});});return;}
if(s.type==="msg"){content(n,"Message System","Hệ thống thông điệp truyền thông","Một hệ message nhiều tầng để vừa có headline lớn, vừa có thông điệp triển khai theo từng touchpoint.",sl=>{sl.addShape(pptx.ShapeType.roundRect,{x:0.9,y:2.14,w:11.55,h:1.7,rectRadius:0.05,fill:{color:C.bd},line:{color:C.bd,pt:0}});t(sl,"CORE TERRITORY",1.18,2.42,1.6,0.16,{fs:10,b:true,c:"BFD5EA"});t(sl,"Bảo Việt giữ cho dòng chảy gia đình không ngừng lại",1.18,2.72,7.7,0.38,{fs:24,b:true,c:C.w});t(sl,"Lãnh thổ lớn để kể về bảo vệ, kế thừa và sự tiếp nối của gia đình Việt.",1.18,3.18,5.8,0.16,{fs:11.5,c:C.w});[["BIG IDEA","Giữ mái chèo di sản",C.g],["SIGN-OFF","Giữ mái chèo hôm nay, chở che muôn thế hệ mai sau",C.b],["SOCIAL SYSTEM","#GiuMaiCheoDiSan  #DongChayKhongNgungLai",C.g]].forEach((a,i)=>{const x=0.9+i*3.9;sl.addShape(pptx.ShapeType.roundRect,{x,y:4.15,w:3.75,h:1.48,rectRadius:0.05,fill:{color:C.w},line:{color:C.ln,pt:1}});sl.addShape(pptx.ShapeType.rect,{x:x+0.14,y:4.28,w:0.06,h:1.05,fill:{color:a[2]},line:{color:a[2],pt:0}});t(sl,a[0],x+0.28,4.3,1.4,0.14,{fs:9.2,c:C.s,b:true});t(sl,a[1],x+0.28,4.58,3.1,0.5,{fs:i===1?17:18,b:true,c:C.bd});});});return;}
if(s.type==="win"){content(n,"Why It Wins","Vì sao ý tưởng này có khả năng chiến thắng cả ở góc nhìn thương hiệu lẫn truyền thông","Một đề xuất thắng lớn là đề xuất chạm đúng ba tầng: ý nghĩa, hình ảnh, và khả năng nhân rộng.",sl=>{[["01","Ý nghĩa rõ ràng","Liên kết tự nhiên giữa đua ghe, người trụ cột và vai trò bảo vệ."],["02","Hình ảnh đủ mạnh","Đồng loạt mái chèo, sông ánh sáng, drone tribute, lời nhắn truyền đời."],["03","Khả năng sở hữu","Naming rights và nghi lễ độc quyền giúp thương hiệu sở hữu tài sản văn hóa mới."],["04","Khả năng tích lũy","Mỗi mùa giải cộng dồn thêm câu chuyện, dữ liệu, nội dung và thiện cảm."]].forEach((a,i)=>{const x=i%2===0?0.9:6.82; const y=i<2?2.22:4.1;sl.addShape(pptx.ShapeType.roundRect,{x,y,w:5.63,h:1.45,rectRadius:0.05,fill:{color:i===1||i===2?C.l:C.w},line:{color:C.ln,pt:1}});pill(sl,a[0],x+0.2,y+0.2,0.52,i===1||i===2?C.g:C.b);t(sl,a[1],x+0.86,y+0.22,2.4,0.2,{fs:17,b:true,c:C.bd});t(sl,a[2],x+0.2,y+0.66,5.0,0.46,{fs:11.4});});t(sl,"Đây không phải creative đặt lên một event. Đây là một asset thương hiệu được sinh ra từ chính tinh thần của event.",0.9,6.05,8.4,0.34,{fs:16,c:C.bd,i:true});});return;}
if(s.type==="wow2"){content(n,"WOW Moment 02","Sông Hương - Dòng Sông Ánh Sáng","Đêm trước ngày đua hoặc thời khắc bế mạc, dòng sông trở thành một installation phát sáng của ký ức và niềm tin.",sl=>{sl.addShape(pptx.ShapeType.roundRect,{x:0.9,y:2.22,w:11.55,h:3.54,rectRadius:0.05,fill:{color:C.bd},line:{color:C.bd,pt:0}});t(sl,"Floating light line + lời nhắn truyền đời",1.18,2.55,4.6,0.24,{fs:19,b:true,c:C.w});["Hệ thống đèn nổi hoặc thuyền ánh sáng tạo thành dải vàng - xanh mang nhận diện Bảo Việt Nhân Thọ.","Các thông điệp 'đi tiếp', 'giữ nhịp', 'chở che' xuất hiện dưới dạng installation hoặc projection mapping ven sông.","Khách tham dự có thể gửi lời nhắn cho gia đình để được hiển thị trên màn hình bờ sông hoặc livestream ticker."].forEach((it,i)=>sl.addText([{text:it,options:{bullet:{indent:12}}}],{x:1.18,y:3.04+i*0.38,w:5.45,h:0.28,fontFace:"Barlow",fontSize:12,color:C.w,margin:0}));card(sl,7.28,3.02,4.1,1.22,"Tác động","Cinematic + shareable","Đủ đẹp cho báo chí, đủ cảm cho công chúng",C.g);card(sl,7.28,4.44,4.1,1.22,"Vai trò thương hiệu","Người giữ ánh sáng tiếp nối","Chuyển hóa từ claim sang trải nghiệm",C.b);});return;}
if(s.type==="journey"){content(n,"Experience Design","Tầm nhìn tổng thể cho ngày diễn ra sự kiện","Không tổ chức một race day. Tổ chức một cultural show day trên mặt nước.",sl=>{[["06:00","Khởi động cộng đồng","Check-in bờ sông, media warm-up, activation đầu ngày"],["07:00","Lễ Tôn Vinh Người Cầm Lái","Nghi thức mở màn tạo dignity và cảm xúc"],["08:00","Đua vòng loại và kể chuyện trực tiếp","MC / livestream layer thêm brand narrative"],["10:30","Không gian activation cộng đồng","Lead capture, lời nhắn gia đình, social challenge"],["14:00","Chung kết + trao cúp","Cao trào cạnh tranh và vinh danh"],["18:30","Closing spectacle","Ánh sáng / drone / lời hẹn mùa sau"]].forEach((m,i)=>{const y=2.22+i*0.58;sl.addShape(pptx.ShapeType.roundRect,{x:0.9,y,w:11.55,h:0.46,rectRadius:0.03,fill:{color:i%2===0?C.l:C.w},line:{color:C.ln,pt:1}});t(sl,m[0],1.12,y+0.13,0.72,0.16,{fs:12.4,b:true,c:C.gd});t(sl,m[1],2.0,y+0.12,3.15,0.16,{fs:12.2,b:true,c:C.bd});t(sl,m[2],5.28,y+0.12,6.1,0.16,{fs:11.1});});});return;}
if(s.type==="imc"){content(n,"IMC Architecture","Kiến trúc IMC tổng thể","Một hệ thống chạm đồng bộ từ truyền thông đại chúng đến trải nghiệm tại chỗ và CRM sau event.",sl=>{[{x:0.9,t:"PHASE 1",s:"Teasing & Meaning Build",d:"Khơi mở biểu tượng người cầm lái và tinh thần giữ dòng chảy gia đình"},{x:4.45,t:"PHASE 2",s:"Explosion & Event Day",d:"Biến giải đua thành national spectacle trên social, livestream và PR"},{x:8.0,t:"PHASE 3",s:"Amplification & Legacy",d:"Kéo dài tài sản nội dung, community goodwill và lead nurturing"}].forEach((p,i)=>{sl.addShape(pptx.ShapeType.roundRect,{x:p.x,y:2.4,w:3.05,h:2.2,rectRadius:0.05,fill:{color:i===1?C.bd:C.w},line:{color:i===1?C.bd:C.ln,pt:1}});t(sl,p.t,p.x+0.2,2.67,0.9,0.16,{fs:10,b:true,c:i===1?C.g:C.gd});t(sl,p.s,p.x+0.2,3.0,2.5,0.28,{fs:16.5,b:true,c:i===1?C.w:C.bd});t(sl,p.d,p.x+0.2,3.48,2.6,0.6,{fs:11,c:i===1?C.w:C.t});});["Owned: social channel BVNT, microsite / landing page, CRM journey","Earned: PR văn hóa - cộng đồng - thương hiệu, KOL review, UGC","Shared: TikTok challenge, reels, livestream clip, media partner social","Paid: OOH chọn lọc tại Huế / Đà Nẵng, digital video, boosting short-form"].forEach((it,i)=>sl.addText([{text:it,options:{bullet:{indent:12}}}],{x:1.05,y:5.08+i*0.22,w:9,h:0.18,fontFace:"Barlow",fontSize:12,color:C.t,margin:0}));});return;}
if(s.type==="phase2"){content(n,"Phase 2","Giai đoạn 2 - Explosion: ngày sự kiện phải bùng nổ về hình ảnh lẫn chia sẻ","Event day là cao trào của chiến dịch, nhưng không được chỉ là phát sóng diễn biến thi đấu.",sl=>{card(sl,0.9,2.24,2.6,1.22,"Livestream","Multi-layer","Có MC, có visual package, có brand story",C.b);card(sl,3.74,2.24,2.6,1.22,"PR nóng","Instant newsroom","Ảnh nhanh, clip nhanh, quote nhanh",C.g);card(sl,6.58,2.24,2.6,1.22,"Social short-form","Reels / TikTok","Cắt ngay từ lễ mở màn, tăng tốc, trao cúp",C.b);card(sl,9.42,2.24,3.03,1.22,"KOL visit","Local x national","Travel, culture, family, sports creators",C.g);["Livestream graphics dùng ngôn ngữ 'giữ nhịp - đi tiếp - chở che' thay vì chỉ scoreboard.","Media zone bố trí sẵn vantage point để đảm bảo có hero shot đẹp cho báo chí và UGC.","Social team dựng realtime content hub ngay tại event để đăng trong vòng 15-30 phút."].forEach((it,i)=>sl.addText([{text:it,options:{bullet:{indent:12}}}],{x:1.05,y:4.06+i*0.24,w:9,h:0.18,fontFace:"Barlow",fontSize:12,color:C.t,margin:0}));quote(sl,"Bùng nổ phải có chủ đích: mọi khoảnh khắc đẹp đều phải dẫn về vai trò thương hiệu.","Nguyên tắc creative day-of");});return;}
if(s.type==="activation"){content(n,"On-ground Activation","Hệ sinh thái activation tại chỗ","Ba lớp activation để chạm cảm xúc, mời tham gia và tạo visual spectacle.",sl=>{[{x:0.9,w:3.45,ttl:"Emotional",hd:"Bến Nhắn Gửi Gia Đình",sub:"Để cảm xúc trở thành điểm chạm thương hiệu",a:C.g,pts:["Viết lời nhắn cho người giữ nhịp trong gia đình","Hiển thị trên màn hình, landing page và social reel"]},{x:4.95,w:3.45,ttl:"Participatory",hd:"Nhịp Chèo Đồng Tâm",sub:"Để người xem thật sự nhập cuộc",a:C.b,pts:["Trò chơi mô phỏng chèo theo nhịp đội","Dùng cho check-in, mini game và data capture"]},{x:9.0,w:3.45,ttl:"Spectacle",hd:"Bức Tường Mái Chèo Di Sản",sub:"Để event có một biểu tượng thị giác riêng",a:C.g,pts:["Installation mái chèo khổng lồ + ánh sáng","Photo point signature của giải đấu"]}].forEach(ca=>{sl.addShape(pptx.ShapeType.roundRect,{x:ca.x,y:2.26,w:ca.w,h:3.72,rectRadius:0.05,fill:{color:C.w},line:{color:C.ln,pt:1}});sl.addShape(pptx.ShapeType.rect,{x:ca.x,y:2.26,w:ca.w,h:0.12,fill:{color:ca.a},line:{color:ca.a,pt:0}});t(sl,ca.ttl.toUpperCase(),ca.x+0.22,2.5,1.6,0.14,{fs:9.5,c:ca.a,b:true});t(sl,ca.hd,ca.x+0.22,2.82,2.7,0.56,{fs:18,b:true,c:C.bd});t(sl,ca.sub,ca.x+0.22,3.48,2.8,0.3,{fs:10.8,c:C.s});ca.pts.forEach((it,i)=>sl.addText([{text:it,options:{bullet:{indent:12}}}],{x:ca.x+0.22,y:4.0+i*0.52,w:ca.w-0.44,h:0.34,fontFace:"Barlow",fontSize:11.2,color:C.t,margin:0}));});});return;}
if(s.type==="film"){content(n,"Hero Film","Định hướng hero film","Một phim ngắn không kể về bảo hiểm, mà kể về người giữ nhịp để khán giả tự hiểu vì sao cần được chở che.",sl=>{sl.addShape(pptx.ShapeType.roundRect,{x:0.9,y:2.22,w:7.1,h:3.7,rectRadius:0.05,fill:{color:C.bd},line:{color:C.bd,pt:0}});t(sl,"Mạch phim đề xuất",1.18,2.5,2.0,0.16,{fs:10,b:true,c:"BFD5EA"});[["01","Nhịp chèo trên sông Hương mở ra câu chuyện"],["02","Người trụ cột hiện lên bền bỉ, lặng lẽ"],["03","Cao trào ở lễ tôn vinh và khoảnh khắc bứt tốc"],["04","Kết phim bằng sign-off như một lời hứa thương hiệu"]].forEach((a,i)=>{const y=2.9+i*0.62;pill(sl,a[0],1.18,y,0.44,i%2===0?C.g:C.b);t(sl,a[1],1.76,y+0.02,5.2,0.18,{fs:13,c:C.w,b:i===0||i===3});});sl.addShape(pptx.ShapeType.roundRect,{x:8.25,y:2.22,w:4.2,h:1.75,rectRadius:0.05,fill:{color:C.w},line:{color:C.ln,pt:1}});t(sl,"Mood & Tone",8.5,2.46,1.6,0.14,{fs:9.5,c:C.gd,b:true});t(sl,"Cinematic | dignified | warm",8.5,2.78,3.15,0.34,{fs:16.5,b:true,c:C.bd});t(sl,"Không melodrama. Không quảng cáo hóa quá sớm.",8.5,3.38,2.9,0.2,{fs:10.8,c:C.s});sl.addShape(pptx.ShapeType.roundRect,{x:8.25,y:4.17,w:4.2,h:1.75,rectRadius:0.05,fill:{color:C.l},line:{color:C.ln,pt:1}});t(sl,"Output",8.5,4.42,1.0,0.14,{fs:9.5,c:C.b,b:true});t(sl,"30s | 60s | documentary cut",8.5,4.78,3.1,0.28,{fs:16.5,b:true,c:C.bd});t(sl,"Dùng cho TVC online, event opening và PR assets.",8.5,5.16,2.9,0.16,{fs:10.8,c:C.s});});return;}
if(s.type==="ecosystem"){content(n,"Content Ecosystem","Hệ sinh thái nội dung","Một idea tốt phải đẻ ra được nhiều format, nhiều vai trò, nhiều độ dài nội dung.",sl=>{[["Hero content","Hero film, teaser main, aftermovie","Build meaning và đẩy scale nhận diện"],["Social storytelling","Reels, TikTok, quote motion, crew stories","Giữ nhịp thảo luận và tương tác"],["Live content","Livestream packages, instant clip, stills","Tối đa hóa khoảnh khắc trong ngày đua"],["PR content","Feature article, interview, photo essay","Củng cố trust và chiều sâu văn hóa"],["CRM content","Follow-up mail, recap page, lead form journey","Chuyển chú ý thành quan tâm thực sự"]].forEach((r,i)=>{const y=2.26+i*0.68;sl.addShape(pptx.ShapeType.roundRect,{x:0.9,y,w:11.55,h:0.54,rectRadius:0.03,fill:{color:i%2===0?C.l:C.w},line:{color:C.ln,pt:1}});t(sl,r[0],1.12,y+0.16,2.0,0.16,{fs:12.1,b:true,c:C.bd});t(sl,r[1],3.12,y+0.16,4.1,0.16,{fs:11.1});t(sl,r[2],7.55,y+0.16,4.2,0.16,{fs:11.1,c:C.s});});});return;}
if(s.type==="lead"){content(n,"Lead Generation","Logic lead generation và nuôi dưỡng sau sự kiện","Sức nóng văn hóa không nên đứng riêng với mục tiêu kinh doanh; hai lớp này cần được nối mượt.",sl=>{card(sl,0.9,2.26,3.55,1.22,"Entry points","QR / Microsite / Activation","Check-in, lời nhắn gia đình, mini game, thông tin event",C.b);card(sl,4.65,2.26,3.55,1.22,"Data layer","Intent-based segmentation","Nhóm quan tâm gia đình, giáo dục con, tích lũy, bảo vệ",C.g);card(sl,8.4,2.26,4.05,1.22,"Follow-up","Content-first nurturing","Recap, câu chuyện ý nghĩa, tư vấn mềm, mời tư vấn khi đúng thời điểm",C.b);["Không ép bán tại event; ưu tiên thu lead bằng giá trị nội dung và cảm xúc.","Tạo hành trình 3 bước: tương tác - nhận nội dung - mở lựa chọn tư vấn.","Đo hiệu quả không chỉ bằng số lead thô, mà bằng chất lượng tương tác và conversion downstream."].forEach((it,i)=>sl.addText([{text:it,options:{bullet:{indent:12}}}],{x:1.05,y:4.22+i*0.24,w:9,h:0.18,fontFace:"Barlow",fontSize:12,color:C.t,margin:0}));});return;}
if(s.type==="impact"){content(n,"Impact","Giá trị kỳ vọng cho Bảo Việt Nhân Thọ","Một nền tảng tốt phải tạo tác động đồng thời lên awareness, trust, perception và business momentum.",sl=>{card(sl,0.9,2.22,2.7,1.12,"Brand impact","Awareness + trust","Độ phủ lớn đi cùng chiều sâu cảm nhận",C.b);card(sl,3.8,2.22,2.7,1.12,"Cultural impact","Relevance + pride","Thương hiệu hiện diện như người gìn giữ",C.g);card(sl,6.7,2.22,2.7,1.12,"Business impact","Lead + momentum","Tạo quan tâm chất lượng thay vì lead thô",C.b);sl.addChart(pptx.ChartType.bar,[{name:"Tác động dự kiến",labels:["Awareness","Trust","Cultural relevance","Social buzz","Lead interest"],values:[88,83,90,86,72]}],{x:0.95,y:3.65,w:5.85,h:2.25,catAxisLabelFontFace:"Barlow",valAxisLabelFontFace:"Barlow",chartColors:[C.b,C.g,C.bd,"3E8DD1",C.gd],showLegend:false,valGridLine:{color:"E6ECF2",pt:1},valAxisMinVal:0,valAxisMaxVal:100,showValue:true,showTitle:false,dataLabelColor:C.t,dataLabelPosition:"outEnd"});sl.addShape(pptx.ShapeType.roundRect,{x:7.05,y:3.65,w:5.4,h:2.25,rectRadius:0.05,fill:{color:C.w},line:{color:C.ln,pt:1}});t(sl,"Perception shift kỳ vọng",7.3,3.9,1.9,0.16,{fs:9.5,c:C.gd,b:true});t(sl,"Từ thương hiệu lớn sang thương hiệu lớn và giàu ý nghĩa.",7.3,4.28,4.5,0.5,{fs:23,b:true,c:C.bd});t(sl,"Một câu chuyện bảo hiểm nhân thọ được kể bằng văn hóa, có quy mô, có chuẩn mực và có khả năng tích lũy dài hạn.",7.3,5.02,4.3,0.42,{fs:11.2});});return;}
if(s.type==="kpi"){content(n,"KPI Framework","Khung KPI đề xuất","Đo theo ba lớp: sức lan tỏa, chất lượng cảm nhận và động lực kinh doanh.",sl=>{t(sl,"BRAND",0.9,2.18,1,0.14,{fs:9.5,c:C.gd,b:true});[["Brand visibility","Reach, impressions, PR mentions, livestream views"],["Brand love & trust","Sentiment, share of positive voice, message association"],["Engagement quality","UGC volume, completion rate, dwell time, participation"]].forEach((r,i)=>{const y=2.46+i*1.02;sl.addShape(pptx.ShapeType.roundRect,{x:0.9,y,w:5.55,h:0.82,rectRadius:0.04,fill:{color:i===1?C.l:C.w},line:{color:C.ln,pt:1}});t(sl,r[0],1.16,y+0.18,2.1,0.18,{fs:13,b:true,c:C.bd});t(sl,r[1],1.16,y+0.42,4.6,0.2,{fs:10.8,c:C.s});});t(sl,"BUSINESS & PROPERTY",6.82,2.18,2.0,0.14,{fs:9.5,c:C.b,b:true});[["Commercial momentum","Lead capture, qualified lead, consultation request"],["Property strength","Partner interest, return intent, year-2 sponsorship premium"]].forEach((r,i)=>{const y=2.46+i*1.02;sl.addShape(pptx.ShapeType.roundRect,{x:6.82,y,w:5.63,h:0.82,rectRadius:0.04,fill:{color:i===0?C.l:C.w},line:{color:C.ln,pt:1}});t(sl,r[0],7.08,y+0.18,2.4,0.18,{fs:13,b:true,c:C.bd});t(sl,r[1],7.08,y+0.42,4.7,0.2,{fs:10.8,c:C.s});});sl.addShape(pptx.ShapeType.roundRect,{x:6.82,y:4.7,w:5.63,h:1.08,rectRadius:0.04,fill:{color:C.bd},line:{color:C.bd,pt:0}});t(sl,"Success = không chỉ reach lớn, mà là mức độ thương hiệu được gắn với vai trò giữ nhịp gia đình và khả năng chuyển hóa thành quan tâm thực sự.",7.08,5.02,4.95,0.44,{fs:13.4,c:C.w,b:true});});return;}
if(s.type==="annual"){content(n,"Long-term Property","Vì sao đây nên trở thành signature property thường niên của Bảo Việt Nhân Thọ","Một signature property mạnh sẽ làm điều mà media buy không làm được: càng lặp lại càng có giá trị.",sl=>{box(sl,0.9,2.18,5.63,3.7,"Năm 1: Birth",["Khóa naming rights và Big Idea.","Sinh ra 3 WOW moments.","Tạo niềm tin rằng đây là cuộc chơi nghiêm túc."],"Objective: ra đời đẹp và đúng.");box(sl,6.82,2.18,5.63,3.7,"Năm 2-3: Scale",["Mở rộng thành cultural week / tourism tie-in / family platform.","Tăng lớp du lịch, giáo dục và di sản.","Định giá lại giá trị tài trợ ở mặt bằng cao hơn."],"Objective: tích lũy tài sản và premium thương hiệu.");});return;}
if(s.type==="close"){const sl=pptx.addSlide();bg(sl);t(sl,"KẾT LUẬN",0.9,1.18,2.4,0.18,{fs:10,c:C.gd,b:true});sl.addShape(pptx.ShapeType.rect,{x:0.9,y:1.72,w:0.08,h:2.15,fill:{color:C.b},line:{color:C.b,pt:0}});sl.addText("Chúng ta không chỉ tài trợ một cuộc đua.\nChúng ta đang giữ cho dòng chảy của hàng ngàn gia đình được tiếp tục.",{x:1.16,y:1.74,w:6.55,h:1.62,fontFace:"Barlow",bold:true,color:C.bd,margin:0,...autoFontSize("Chúng ta không chỉ tài trợ một cuộc đua.\nChúng ta đang giữ cho dòng chảy của hàng ngàn gia đình được tiếp tục.","Barlow",{x:1.16,y:1.74,w:6.55,h:1.62,fontSize:24,minFontSize:21,maxFontSize:27,bold:true,margin:0,mode:"auto"})});t(sl,"Bảo Việt Nhân Thọ có cơ hội biến một giải đua ghe thành signature cultural property mang tên mình, sống cùng gia đình Việt qua nhiều mùa tiếp theo.",1.16,3.62,5.95,0.5,{fs:13.5});sl.addShape(pptx.ShapeType.roundRect,{x:8.1,y:1.92,w:4.35,h:2.85,rectRadius:0.05,fill:{color:C.bd},line:{color:C.bd,pt:0}});t(sl,"Closing line",8.38,2.18,1.4,0.14,{fs:9.5,c:"BFD5EA",b:true});t(sl,"Giữ mái chèo hôm nay, chở che muôn thế hệ mai sau.",8.38,2.52,3.45,0.64,{fs:22,b:true,c:C.w});pill(sl,"GIỮ MÁI CHÈO DI SẢN",1.16,5.1,2.45,C.g);pill(sl,"BOARDROOM-READY | CULTURAL | SCALABLE",3.8,5.1,3.65,C.b);finalize(sl,n);return;}
});
(async()=>{const out=path.join(__dirname,"output","BVNT_Hue_Boat_Race_Proposal_2026_v2.pptx");await pptx.writeFile({fileName:out});console.log(`Wrote ${out}`);})();









