"use strict";
const pptxgen=require("pptxgenjs");
const {autoFontSize,imageSizingCrop,warnIfSlideHasOverlaps,warnIfSlideElementsOutOfBounds}=require("./pptxgenjs_helpers");
const path=require("path");
const pptx=new pptxgen();
pptx.layout="LAYOUT_WIDE";
pptx.author="OpenAI Codex";
pptx.company="Bảo Việt Nhân Thọ";
pptx.lang="vi-VN";
pptx.theme={headFontFace:"Barlow",bodyFontFace:"Barlow",lang:"vi-VN"};
const W=13.333,H=7.5;
const C={navy:"113E68",navy2:"0D2D49",blue:"0B6CB8",gold:"D8A12A",gold2:"E8C15D",white:"FFFFFF",text:"EAF1F8",muted:"C8D4E2",line:"7EA9D0"};
const imgDir="D:/BRAVO/baoviet-pitch-deck/public/Images";
const I={cover:path.join(imgDir,"ảnh bìa.jpg"),race1:path.join(imgDir,"5-dua-ghe-song-huong.jpg"),race2:path.join(imgDir,"dua_22-1693633071517.jpg"),race3:path.join(imgDir,"wm_8775_h11.jpg"),river:path.join(imgDir,"song-huong-scaled.jpg"),hue:path.join(imgDir,"Phu_Văn_lâu.jpg"),logo:path.join(imgDir,"logo-bao-viet-inkythuatso-01.png")};
function bg(sl,img,ov=20){sl.addImage({path:img,...imageSizingCrop(img,0,0,W,H)});sl.addShape(pptx.ShapeType.rect,{x:0,y:0,w:W,h:H,fill:{color:C.navy,transparency:ov},line:{color:C.navy,pt:0}});} 
function header(sl,title,sub){sl.addShape(pptx.ShapeType.rect,{x:0,y:0,w:W,h:0.9,fill:{color:C.navy,transparency:2},line:{color:C.navy,pt:0}});sl.addImage({path:I.logo,x:10.4,y:0.12,w:2.25,h:0.5});sl.addText(title,{x:0.64,y:0.18,w:8.8,h:0.26,fontFace:"Barlow",fontSize:23,bold:true,color:C.gold,margin:0});if(sub)sl.addText(sub,{x:0.64,y:0.48,w:7.8,h:0.14,fontFace:"Barlow",fontSize:9.5,color:C.white,margin:0});}
function footer(sl,n){sl.addShape(pptx.ShapeType.rect,{x:0,y:7.0,w:W,h:0.5,fill:{color:C.navy,transparency:10},line:{color:C.navy,pt:0}});sl.addText(String(n).padStart(2,"0"),{x:12.45,y:7.12,w:0.28,h:0.12,fontFace:"Barlow",fontSize:9,bold:true,color:C.gold,margin:0,align:"right"});warnIfSlideHasOverlaps(sl,pptx);warnIfSlideElementsOutOfBounds(sl,pptx);} 
function panel(sl,x,y,w,h,a=8){sl.addShape(pptx.ShapeType.roundRect,{x,y,w,h,rectRadius:0.05,fill:{color:C.navy2,transparency:a},line:{color:C.line,pt:1}});} 
function card(sl,x,y,w,h,title,body,accent=C.gold){panel(sl,x,y,w,h,6);sl.addShape(pptx.ShapeType.rect,{x:x+0.18,y:y+0.16,w:w-0.36,h:0.04,fill:{color:accent},line:{color:accent,pt:0}});sl.addText(title,{x:x+0.22,y:y+0.28,w:w-0.44,h:0.22,fontFace:"Barlow",fontSize:14,bold:true,color:C.white,margin:0});sl.addText(body,{x:x+0.22,y:y+0.62,w:w-0.44,h:h-0.78,fontFace:"Barlow",fontSize:10.6,color:C.muted,margin:0,breakLine:true});}
function bullets(sl,items,x,y,w,step=0.44,fs=12.6){items.forEach((it,i)=>sl.addText([{text:it,options:{bullet:{indent:12}}}],{x,y:y+i*step,w,h:0.24,fontFace:"Barlow",fontSize:fs,color:C.white,margin:0}));}
function split(sl,opt){bg(sl,opt.img,opt.ov??28);header(sl,opt.title,opt.sub);panel(sl,0.7,1.18,opt.leftW??5.9,5.45,10);sl.addText(opt.head,{x:1.0,y:1.54,w:(opt.leftW??5.9)-0.6,h:0.5,fontFace:"Barlow",fontSize:20,bold:true,color:C.white,margin:0});if(opt.points)bullets(sl,opt.points,1.0,2.24,(opt.leftW??5.9)-0.65,opt.step??0.48,opt.fs??12.6);if(opt.note){sl.addShape(pptx.ShapeType.roundRect,{x:1.0,y:5.52,w:(opt.leftW??5.9)-0.65,h:0.7,rectRadius:0.04,fill:{color:C.gold,transparency:10},line:{color:C.gold,pt:0}});sl.addText(opt.note,{x:1.18,y:5.74,w:(opt.leftW??5.9)-1.0,h:0.16,fontFace:"Barlow",fontSize:10.5,bold:true,color:C.navy,margin:0,align:"center"});} }
function cover(sl){bg(sl,I.cover,18);sl.addShape(pptx.ShapeType.rect,{x:0,y:0,w:W,h:1.05,fill:{color:C.navy,transparency:2},line:{color:C.navy,pt:0}});sl.addImage({path:I.logo,x:0.72,y:0.2,w:2.75,h:0.6});sl.addText("GIẢI VÔ ĐỊCH ĐUA GHE TRUYỀN THỐNG CỐ ĐÔ HUẾ 2026",{x:0.72,y:1.3,w:9.5,h:0.62,fontFace:"Barlow",fontSize:27,bold:true,color:C.white,margin:0});sl.addText("TRANH CÚP BẢO VIỆT NHÂN THỌ",{x:0.72,y:1.98,w:6.8,h:0.28,fontFace:"Barlow",fontSize:18,bold:true,color:C.gold2,margin:0});panel(sl,0.72,5.32,3.55,0.78,0);sl.addText("ĐỀ XUẤT TỔ CHỨC SỰ KIỆN",{x:0.98,y:5.62,w:3.0,h:0.16,fontFace:"Barlow",fontSize:11,bold:true,color:C.gold,margin:0,align:"center"});}
let n=1;
{const sl=pptx.addSlide();cover(sl);footer(sl,n++);} 
{const sl=pptx.addSlide();split(sl,{img:I.race1,title:"1. EVENT OVERVIEW",sub:"Tổng quan sự kiện",head:"Sự kiện thể thao - văn hóa nổi bật trên sông Hương",points:["Thời gian tổ chức: 02/09/2026, dự kiến 06:30 - 12:00.","Địa điểm: khu vực Phu Văn Lâu - Phú Xuân, sông Hương, Huế.","Quy mô dự kiến: 16-20 ghe, khoảng 400-480 VĐV.","Khán giả trực tiếp: 5.000 - 10.000 người, có livestream hỗ trợ.","Tính chất: sự kiện thể thao truyền thống kết hợp trải nghiệm cộng đồng và tài trợ."],note:"Slide này giúp khách hàng nắm nhanh quy mô, thời gian, địa điểm và tính chất sự kiện."});footer(sl,n++);} 
{const sl=pptx.addSlide();split(sl,{img:I.hue,title:"2. EVENT OBJECTIVES & MEANING",sub:"Mục tiêu & ý nghĩa",head:"Một sự kiện mang tính chào mừng, gìn giữ và thu hút cộng đồng",points:["Chào mừng Quốc khánh 2/9 bằng hoạt động thể thao truyền thống đặc trưng Huế.","Gìn giữ và tôn vinh giá trị đua ghe trên sông Hương.","Nâng tầm giải đua thành sự kiện có tổ chức chuyên nghiệp, hấp dẫn tài trợ.","Tạo điểm hẹn cộng đồng cho người dân, du khách và truyền thông.","Xây dựng hình ảnh hiện diện tích cực và rõ ràng cho Bảo Việt Nhân Thọ."],note:"Slide này cho thấy sự kiện có ý nghĩa xã hội, hình ảnh và tài trợ rõ ràng."});footer(sl,n++);} 
{const sl=pptx.addSlide();bg(sl,I.race2,24);header(sl,"3. COMPETITION FORMAT","Thể thức thi đấu");panel(sl,0.7,1.18,12.0,5.42,10);card(sl,1.0,1.54,3.6,1.6,"Quy mô đội thi","16-20 ghe, mỗi đơn vị 1 ghe, tối đa 10-12 VĐV mỗi lượt.");card(sl,4.86,1.54,3.6,1.6,"Nội dung chính","Nam, nữ, phối hợp nam nữ và các nội dung theo điều lệ.");card(sl,8.72,1.54,3.6,1.6,"Cấu trúc thi đấu","Vòng loại, bán kết, chung kết tùy số lượng đội thực tế.");card(sl,1.0,3.5,3.6,1.6,"Giải thưởng","Giải nội dung, giải tập thể và giải toàn đoàn.");card(sl,4.86,3.5,3.6,1.6,"Vận hành chuyên môn","Có trọng tài, điều hành đường đua và kiểm soát kỹ thuật ghe.");card(sl,8.72,3.5,3.6,1.6,"Lợi ích trình bày","Khách hàng nhìn thấy format thi đấu rõ, dễ hiểu, dễ vận hành.");footer(sl,n++);} 
{const sl=pptx.addSlide();bg(sl,I.river,24);header(sl,"4. EVENT TIMELINE","Timeline ngày sự kiện");panel(sl,0.72,1.2,12.0,5.4,10);[["05:30 - 06:15","Tập kết đội ghe, kiểm tra kỹ thuật, ổn định lực lượng."],["06:15 - 06:45","Đón khách, ổn định khán giả, khởi động MC và âm thanh."],["06:45 - 07:15","Lễ khai mạc, nghi thức mở dòng, giới thiệu đội thi."],["07:15 - 10:30","Các lượt đua chính, bình luận trực tiếp, tương tác khán giả."],["10:30 - 11:15","Chung kết, trao giải phụ, công bố các hạng mục nổi bật."],["11:15 - 12:00","Trao cúp, chụp ảnh tập thể, kết thúc chương trình."]].forEach((r,i)=>{const y=1.58+i*0.78;panel(sl,1.0,y,10.9,0.56,4);sl.addText(r[0],{x:1.22,y:y+0.17,w:1.45,h:0.14,fontFace:"Barlow",fontSize:12,bold:true,color:C.gold,margin:0});sl.addText(r[1],{x:2.82,y:y+0.16,w:8.65,h:0.16,fontFace:"Barlow",fontSize:11.4,color:C.white,margin:0});});footer(sl,n++);} 
{const sl=pptx.addSlide();split(sl,{img:I.race3,title:"5. OPENING CEREMONY",sub:"Nghi thức khai mạc",head:"Mở màn trang trọng để nâng tầm sự kiện",points:["Trống hội hoặc hiệu lệnh khai mạc tạo khí thế đầu chương trình.","Giới thiệu đại biểu, đơn vị tổ chức, nhà tài trợ và các đội thi.","Nghi thức khai dòng / khai cuộc ngay trên sông tạo điểm nhấn văn hóa.","Các ghe đồng loạt vào vị trí, tạo đội hình đẹp trước giờ xuất phát.","Hero moment đề xuất: toàn bộ đội nâng mái chèo đồng loạt chào khai mạc."],note:"Khai mạc là khoảnh khắc đầu tiên để khách mời cảm nhận sự chuyên nghiệp."});footer(sl,n++);} 
{const sl=pptx.addSlide();split(sl,{img:I.race1,title:"6. MAIN RACE EXPERIENCE",sub:"Trải nghiệm đường đua chính",head:"Đường đua phải vừa sôi động vừa dễ theo dõi",points:["Các lượt đua diễn ra liên tục, nhịp nhanh, tạo năng lượng cao trên mặt nước.","MC bình luận trực tiếp giúp khán giả nhận diện đội thi và diễn biến.","Hệ cờ hiệu, âm thanh, điều hành đường đua hỗ trợ không khí và an toàn.","Các thời khắc xuất phát, bứt tốc, về đích được khai thác mạnh về hình ảnh.","Trọng tài, cano hỗ trợ và điều hành luôn bám sát toàn tuyến."],note:"Slide này chứng minh sự kiện không chỉ có thi đấu mà còn có trải nghiệm xem hấp dẫn."});footer(sl,n++);} 
{const sl=pptx.addSlide();split(sl,{img:I.river,title:"7. AUDIENCE EXPERIENCE",sub:"Trải nghiệm khán giả",head:"Khán giả không chỉ đứng xem, mà được tham gia vào không khí sự kiện",points:["Khu vực xem đua được phân luồng rõ và thuận tiện tiếp cận.","Bố trí family viewing zone cho gia đình, khách mời và nhóm khán giả trung tâm.","Có điểm thông tin chương trình, check-in và khu hỗ trợ khán giả.","MC liên tục cập nhật diễn biến để giữ kết nối với khán giả hai bờ.","Các khoảnh khắc đẹp được đẩy mạnh để khán giả dễ hòa nhịp và chia sẻ."],note:"Khách hàng thấy rõ sự kiện có trải nghiệm khán giả chứ không chỉ tập trung vào đội thi."});footer(sl,n++);} 
{const sl=pptx.addSlide();bg(sl,I.race2,24);header(sl,"8. SIDE ACTIVITIES & ENGAGEMENT","Hoạt động bên lề và tương tác");panel(sl,0.72,1.18,12.0,5.44,10);card(sl,0.98,1.5,3.7,1.5,"Boat Decoration Competition","Thi trang trí ghe theo sáng tạo, bản sắc văn hóa, tác động thị giác; có thể thêm bình chọn khán giả.");card(sl,4.82,1.5,3.7,1.5,"Team Uniform Identity","Mỗi đội có màu hoặc chủ đề riêng, khuyến khích đưa họa tiết gợi Huế và yếu tố truyền thống.");card(sl,8.66,1.5,3.36,1.5,"Check-in / Photo Area","Backdrop lớn, khung mái chèo, cổng ghe và installation chủ đề sông nước.");card(sl,0.98,3.34,3.7,1.5,"Team Photography","Chụp ảnh chuyên nghiệp cho từng đội trước giờ đua để phục vụ media và màn hình sự kiện.");card(sl,4.82,3.34,3.7,1.5,"Audience Mini Games","Dự đoán đội thắng, quét QR tham gia, lucky draw và bình chọn đội được yêu thích nhất.");card(sl,8.66,3.34,3.36,1.5,"Additional Ideas","Khu xem gia đình, chèo mini cho trẻ em, Ca Huế trên sông, booth thương hiệu, giải 'Best Moment'.");footer(sl,n++);} 
{const sl=pptx.addSlide();bg(sl,I.race3,24);header(sl,"9. AWARD SYSTEM","Hệ thống giải thưởng");panel(sl,0.78,1.3,11.86,5.2,10);card(sl,1.02,1.7,3.46,1.7,"Giải chính","Cúp, tiền thưởng và quà hiện vật cho các hạng mục thắng cuộc.");card(sl,4.92,1.7,3.46,1.7,"Giải tập thể","Giải toàn đoàn và các hạng mục tổng hợp theo kết quả thi đấu.");card(sl,8.82,1.7,3.46,1.7,"Giải phụ","Ghe ấn tượng nhất, Đội được yêu thích nhất, Khoảnh khắc đẹp nhất đường đua.");card(sl,2.98,3.88,7.36,1.4,"Ý nghĩa","Lễ trao giải gọn, trang trọng và có hình ảnh đẹp sẽ là điểm kết thúc mạnh cho toàn chương trình.",C.gold2);footer(sl,n++);} 
{const sl=pptx.addSlide();split(sl,{img:I.hue,title:"10. BRANDING & SPONSORSHIP INTEGRATION",sub:"Tích hợp thương hiệu & quyền lợi tài trợ",head:"Hiện diện tài trợ rõ ràng, đẹp mắt và đúng bối cảnh sự kiện",points:["Tên giải đấu gắn trực tiếp với Bảo Việt Nhân Thọ.","Logo hiện diện trên ghe, đồng phục, băng đầu, sân khấu và backdrop.","Hệ cờ, banner, cổng chào và visual ven sông được đồng bộ nhận diện.","Nhà tài trợ được nhắc trong khai mạc, bình luận và trao giải.","Có thể bố trí booth hoặc không gian tương tác thương hiệu tại khu khán giả."],note:"Slide này giúp khách hàng hình dung rất rõ tài trợ sẽ xuất hiện ở đâu và bằng cách nào."});footer(sl,n++);} 
{const sl=pptx.addSlide();split(sl,{img:I.river,title:"11. ON-SITE MEDIA & COMMUNICATION",sub:"Media và truyền thông hiện trường",head:"Tăng độ phủ bằng cách ghi lại đúng khoảnh khắc ngay tại sự kiện",points:["Livestream trực tiếp các lượt đua chính và lễ trao giải.","MC bình luận xuyên suốt để giữ nhịp chương trình.","Đội quay phim, chụp ảnh, drone ghi lại toàn cảnh và các điểm nhấn.","Khu vực media được bố trí vị trí đẹp cho báo chí và social content.","Ảnh đội thi, check-in và khoảnh khắc về đích được xử lý nhanh trong ngày."],note:"Sự kiện được mở rộng độ phủ thực tế bằng media hiện trường, không chỉ bằng quảng bá trước đó."});footer(sl,n++);} 
{const sl=pptx.addSlide();bg(sl,I.cover,24);header(sl,"12. EXPECTED IMPACT","Tác động kỳ vọng");panel(sl,0.74,1.24,6.2,5.36,8);sl.addText("Sự kiện rõ tổ chức - đẹp hình ảnh - tốt tài trợ",{x:1.0,y:1.62,w:5.6,h:0.8,fontFace:"Barlow",fontSize:24,bold:true,color:C.white,margin:0});bullets(sl,["Tạo một sự kiện văn hóa - thể thao có hình ảnh mạnh và dễ thu hút công chúng.","Nâng cao sức hút của đua ghe truyền thống trong dịp Quốc khánh tại Huế.","Gia tăng trải nghiệm cho đội thi, khán giả và khách mời bằng hoạt động bên lề.","Tạo khối lượng ảnh, video và tư liệu mạnh cho truyền thông sau sự kiện.","Khẳng định Bảo Việt Nhân Thọ là nhà tài trợ đồng hành cùng sự kiện cộng đồng có bản sắc."],1.0,2.62,5.4,0.52,12.2);panel(sl,7.3,1.66,5.2,1.4,0);sl.addText("Kết quả mong muốn",{x:7.62,y:1.98,w:1.8,h:0.16,fontFace:"Barlow",fontSize:10,bold:true,color:C.gold,margin:0});sl.addText("Một sự kiện đáng tài trợ, dễ truyền thông và đủ hấp dẫn để tiếp tục nâng cấp trong các mùa sau.",{x:7.62,y:2.3,w:4.56,h:0.44,fontFace:"Barlow",fontSize:14,bold:true,color:C.white,margin:0});footer(sl,n++);} 
(async()=>{const out=path.join(__dirname,"output","BVNT_Hue_EventPlan_Visual_v2.pptx");await pptx.writeFile({fileName:out});console.log(`Wrote ${out}`);})();
